services:
  exchange-server:
    pull_policy: build
    build:
      context: src/exchange
      dockerfile: Dockerfile
    image: landscape-locust/exchange-server:latest
    container_name: landscape-locust-exchange
    ports:
      - "9999:9999"
    environment:
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_PORT=9999
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_DB_HOST=landscape-postgres
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_DB_NAME=landscape-test-main
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_DB_USER=landscape
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_DB_PASSWORD=landscape
      - LANDSCAPE_LOCUST_EXCHANGE_SERVER_DB_PORT=5432
    networks:
      - landscape-locust-network
      - landscape-net
    restart: unless-stopped

  locust-ping-master:
    pull_policy: build
    build:
      context: src/locustfiles
      dockerfile: Dockerfile
    image: landscape-locust:latest
    container_name: locust-ping-master
    ports:
      - "8092:8089"
    environment:
      - LOCUST_MODE=master
      - LOCUST_LOCUSTFILE=ping.py
      - LOCUST_HOST=${LANDSCAPE_HOST:-http://landscape-haproxy}
    command: >
      locust --master --locustfile ping.py --host ${LANDSCAPE_HOST:-http://landscape-haproxy} --headless --users ${LOCUST_USERS:-100000} --spawn-rate ${LOCUST_SPAWN_RATE:-250} --expect-workers 8 --web-host 0.0.0.0
    networks:
      - landscape-locust-network
      - landscape-net
    depends_on:
      - exchange-server

  locust-ping-worker:
    image: landscape-locust:latest
    pull_policy: build
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER_NODE_HOST=locust-ping-master
      - LOCUST_LOCUSTFILE=ping.py
    command: >
      locust --worker --master-host locust-ping-master --locustfile ping.py
    networks:
      - landscape-locust-network
      - landscape-net
    depends_on:
      - locust-ping-master
    deploy:
      replicas: 8

  locust-message-master:
    image: landscape-locust:latest
    container_name: locust-message-master
    pull_policy: build
    ports:
      - "8090:8089"
    environment:
      - LOCUST_MODE=master
      - LOCUST_LOCUSTFILE=message.py
      - LOCUST_HOST=${LANDSCAPE_HOST:-http://landscape-haproxy}
    command: >
      locust --master --locustfile message.py --host ${LANDSCAPE_HOST:-http://landscape-haproxy} --headless --users ${LOCUST_USERS:-100000} --spawn-rate ${LOCUST_SPAWN_RATE:-250} --expect-workers 8 --web-host 0.0.0.0
    networks:
      - landscape-locust-network
      - landscape-net
    depends_on:
      - exchange-server

  locust-message-worker:
    image: landscape-locust:latest
    pull_policy: build
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER_NODE_HOST=locust-message-master
      - LOCUST_LOCUSTFILE=message.py
    command: >
      locust --worker --master-host locust-message-master --locustfile message.py
    networks:
      - landscape-locust-network
      - landscape-net
    depends_on:
      - locust-message-master
    deploy:
      replicas: 8

  locust-api-master:
    image: landscape-locust:latest
    pull_policy: build
    container_name: locust-api-master
    ports:
      - "8091:8089"
    environment:
      - LOCUST_MODE=master
      - LOCUST_LOCUSTFILE=api.py
      - LOCUST_HOST=${LANDSCAPE_HOST:-http://landscape-haproxy}
    command: >
      locust --master --locustfile api.py --host ${LANDSCAPE_HOST:-http://landscape-haproxy} --headless --users ${LOCUST_USERS:-100000} --spawn-rate ${LOCUST_SPAWN_RATE:-250} --expect-workers 8 --web-host 0.0.0.0
    networks:
      - landscape-locust-network
      - landscape-net

  locust-api-worker:
    image: landscape-locust:latest
    pull_policy: build
    environment:
      - LOCUST_MODE=worker
      - LOCUST_MASTER_NODE_HOST=locust-api-master
      - LOCUST_LOCUSTFILE=api.py
    command: >
      locust --worker --master-host locust-api-master --locustfile api.py
    networks:
      - landscape-locust-network
      - landscape-net
    depends_on:
      - locust-api-master
    deploy:
      replicas: 8

networks:
  landscape-locust-network:
    driver: bridge
  landscape-net:
    external: true
    name: landscape-dev_landscape-net
